### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by nikita-astronaut**
Added gradient of variance and more customized hamiltonians. Edge now contains J and sign of transform (-1 for AB and BA terms) and (+1 for AA, BB terms)

### CODE REVIEW

**Comment by twesterhout** [comment]
* How can the user decide whether the variance gradient is used? How about changing the weight of the gradient (it's currently hard-coded to `1e-2`)?
* How are the Hamiltonians constructed, i.e. what's the new file format?
* The implementation of `energy2` looks scary. Does it have to be that involved?

**Comment by twesterhout** [comment]
Basically, the real show-stopper here is the absence of command line arguments allowing people to control how the variance is used. Could you add them?

**Comment by nikita-astronaut** [comment]
> * How can the user decide whether the variance gradient is used? How about changing the weight of the gradient (it's currently hard-coded to `1e-2`)?
> * How are the Hamiltonians constructed, i.e. what's the new file format?
> * The implementation of `energy2` looks scary. Does it have to be that involved?

I have added the command line argument which weights gradient of E_loc and variance as (1 - delta) * grad_of_Eloc + delta * grad_of_variance.

In energy2, we consider all possible combinations of pairs (i, j), (k, l) coming from the first and the second hamiltonians. These pairs can intersect, or the first pairs flips a pair of spins and the action of the second pair is different (depends on the action of the first pair). I believe, in infinite volume this all is unimportant, but for small number of spins this is necessary. This is why it looks so scary.

Though, I have checked, this thing does reduce performance too much.

**Comment by twesterhout** [comment]
> Though, I have checked, this thing does reduce performance too much.

Yeah, so it'd be great to use `None` or something as the coefficient to completely disable the computation of `energy2`. I'll give it try in a few days (probably during weekend :)).

@nikita-astronaut btw, which formulae did you use? Was is the `.pdf` you sent to the Telegram chat some time ago? If it's not too much trouble, could you add `.tex` sources and the `.pdf` to the repo as well? Just as a reference.

**Pull request closed without merging**
